kind: ConfigMap
apiVersion: v1
metadata:
  namespace: jitsi
  name: web-shard-config
data:
  # custom footer that references Schul Cloud imprint and data privacy protection
   SHARD_NAME: "shard1"
   OCTO_REGION: "tor-1"
   USER_REGION: "tor-1"